defaults:
  services:
    max-memory: 1gb
    max-cpus: 0.5
override:
  services:
    accounting-v3:
      max-memory: 512mb
    logstash:
      max-memory: 2gb
    rollunnet-php:
      max-memory: 4gb
      max-cpus: 2
    mws-inv-php:
      max-memory: 2gb
