name: Deploy

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        # 49.12.211.84 - https://panel.rollun.net/hosts/hetzner-01-test
        # 88.99.186.92 - https://panel.rollun.net/hosts/hetzner-03
        # 5.75.224.231 - https://panel.rollun.net/hosts/rollun-crm
        host: "49.12.211.84,88.99.186.92,5.75.224.231"
        username: "root"
        key: ${{ secrets.CI_CD_SSH_KEY }}
        script: |
          source .nvm/nvm.sh # add npm to PATH for current session
          curl -s https://raw.githubusercontent.com/rollun-com/devops-docker-limits/master/update.sh | bash
